seymour/urls.py
from django.conf import settings
from django.conf.urls.defaults import *


urlpatterns = patterns('',
    # static files (images, css, js)
    # it is recommended that you setup your webserver to serve these files
    # this is just handy as a fallback for the dev server.
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    
    # accounts    
    (r'^login/openid/$', 'seymour.accounts.views.login_openid_callback'),
    (r'^login/$', 'seymour.accounts.views.login'),
    (r'^signup/openid/$', 'seymour.accounts.views.signup_openid_callback'),
    (r'^signup/$', 'seymour.accounts.views.signup'),    
    (r'^reset/$', 'seymour.accounts.views.reset_password'),
    (r'^confirm-reset/((?P<email>[^/]+)/?)?((?P<code>[^/]+)/)?$', 'seymour.accounts.views.confirm_reset'),
    (r'^profile/$', 'seymour.accounts.views.profile'),
    (r'^captcha/(?P<hexhash>[^/]+)/', 'seymour.accounts.views.captcha'),
    
    # feeds        
    (r'^feeds/unread/$', 'seymour.feeds.views.unread_feeds'),
    (r'^feeds/manage/$', 'seymour.feeds.views.manage_feeds'),
    (r'^feeds/export/$', 'seymour.feeds.views.export_feeds'),    
    (r'^feeds/add/', 'seymour.feeds.views.add_feed'),
    (r'^feeds/(?P<slug>[^/]+)/edit/', 'seymour.feeds.views.edit_feed'),
    (r'^feeds/(?P<slug>[^/]+)/', 'seymour.feeds.views.view_feed'),
    (r'^feeds/$', 'seymour.feeds.views.feeds'),
    (r'^$', 'seymour.feeds.views.home'),
)

seymour/accounts/models.py
import datetime
from django.db import models, connection
from seymour.feeds.models import Feed, Item, AccountFeed


class Account(models.Model):
    openid = models.CharField('openid', max_length=255, null=True)
    firstname = models.CharField('first name', max_length=100, null=True)
    lastname = models.CharField('last name', max_length=100, null=True)
    email = models.EmailField('e-mail address', null=True)
    date_joined = models.DateTimeField('date joined', default=datetime.datetime.now, db_index=True)
    last_login = models.DateTimeField('last login', null=True, db_index=True)
    password_salt = models.CharField('password salt', max_length=100, null=True)
    password_hash = models.CharField('password hash', max_length=100, null=True)
    confirmation_code = models.CharField('confirmation code', max_length=50, null=True, db_index=True)
    is_active = models.BooleanField('active', default=True, db_index=True)    
    
    class Meta:
        db_table = 'accounts'
        unique_together = (('email', 'openid'),)
        ordering = ['email', 'openid']
        
    def get_fullname(self):
        if self.firstname or self.lastname:            
            return u"%s %s" % (self.firstname, self.lastname)
        else:
            return None
    fullname = property(get_fullname)
        
    def set_password(self, raw_password):
        import random
        import sha
                        
        salt = sha.new(str(random.random())).hexdigest()[:5]        
        hsh = sha.new(salt+raw_password).hexdigest()
        self.password_salt = salt
        self.password_hash = hsh        

    def check_password(self, raw_password):
        """
        Returns a boolean of whether the raw_password was correct.
        """

        import random
        import sha
                
        hsh = sha.new(self.password_salt+raw_password).hexdigest()
        return self.password_hash == hsh
        
    def get_all_feeds(self):
        """Return all feeds associated with this account"""
                
        return self.accountfeed_set.select_related().filter().order_by('feeds.title')
    
    def get_unread_feeds(self):
        """Return a list of unread feeds for this account. Each feed has 
           unread_total filled in."""

        sql = """
SELECT items.feed_id, count(*)
FROM items
INNER JOIN accounts_feeds ON accounts_feeds.feed_id = items.feed_id
WHERE accounts_feeds.account_id = %s AND 
      (items.date_added > accounts_feeds.latest_read OR accounts_feeds.latest_read IS NULL)
GROUP BY items.feed_id
        """ % (self.id,)
        
        cursor = connection.cursor()
        cursor.execute(sql)
        
        feed_totals = {}
        for row in cursor.fetchall():
            feed_id, total_items = row             
            feed_totals[feed_id] = total_items
        
        feed_ids = feed_totals.keys()
        
        if feed_ids:            
            accountfeeds = AccountFeed.objects.select_related().filter(account=self, feed__id__in=feed_ids).order_by('feeds.title')
            for af in accountfeeds:
                af.feed.unread_total = feed_totals[af.feed.id]

            return accountfeeds
            
        else:
            return []
            
    def save(self):
        # TODO: What would be the best standard exception here?
        #       (This should be picked up by form validation already)
        
        if self.email and self.openid:
            raise Exception() 
        if not self.email and not self.openid:
            raise Exception()            
        if self.openid and (self.password_salt or self.password_hash):
            raise Exception()
        if self.email and not (self.password_salt and self.password_hash):
            raise Exception()
            
        super(Account, self).save()

seymour/accounts/forms.py
from django.conf import settings
from django import forms
from seymour.accounts.models import Account


__all__ = (
    'LoginForm', 'SignupForm', 
    'ResetPasswordForm', 'ConfirmResetPasswordForm', 
    'EditOpenIDProfileForm', 'EditEmailProfileForm'
)

    
class LoginForm(forms.Form):
    method = forms.ChoiceField(label='Login using', required=True, choices=(('email', 'Email & Password'), ('openid', 'OpenID')), widget=forms.RadioSelect())
    
    openid = forms.CharField(label='Your OpenID', max_length=255, required=False, widget=forms.TextInput(attrs={'class': 'text'}))
    
    email = forms.EmailField(label='Email address', max_length=75, required=False, widget=forms.TextInput(attrs={'class': 'text'}))
    password = forms.CharField(label='Password', max_length=30, required=False, widget=forms.PasswordInput(attrs={'class': 'text'}))
    
    
    def clean(self):
        if self.cleaned_data['method'] == 'email':
            email = self.cleaned_data.get('email') 
            password = self.cleaned_data.get('password')
            
            # must I use a forms.ValidationError()? must this be a sequence?
            # the documentation isn't clear..
            if not email:
                self.errors['email'] = "This field is required."            
            if not password:
                self.errors['password'] = "This field is required."
            
            if email and password:        
                try:
                    account = Account.objects.get(email=email)                
                except Account.DoesNotExist:               
                    self.data['password'] = ''
                    raise forms.ValidationError("Please enter a correct email address and password. Note that both fields are case-sensitive.")
                
                if not account.check_password(password):
                    self.data['password'] = ''                
                    raise forms.ValidationError("Please enter a correct email address and password. Note that both fields are case-sensitive.")
                    
                if not account.is_active:
                    raise forms.ValidationError("This account is inactive.")
    
                self._account = account
                
                return self.cleaned_data
        
        else:
            # TODO: do some basic checks to make sure this is actually a URL..            
            return self.cleaned_data
    
    def get_openid(self):
        # for now handle it all inside the view
        return self.cleaned_data['openid']        
    
    def get_account(self):        
        if hasattr(self, '_account'):
            return self._account
        else:
            return None    


email_help = """Please use a valid email address as you will use this to log-in.
We will never sell your email address to anyone."""
password_help = """Password should be at least 6 characters."""
confirmation_help = """We sent you this in an email. If you clicked the link we
sent it should automatically be filled in."""

class SignupForm(forms.Form):
    method = forms.ChoiceField(label='Signup using', required=True, choices=(('email', 'Email & Password'), ('openid', 'OpenID')), widget=forms.RadioSelect())
    
    openid = forms.CharField(label='Your OpenID', max_length=255, required=False, widget=forms.TextInput(attrs={'class': 'text'})) 
    
    firstname = forms.CharField(label='First name', max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'text'}))
    lastname = forms.CharField(label='Last name', max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'text'}))
    email = forms.EmailField(label='Email address', help_text=email_help, max_length=75, required=False, widget=forms.TextInput(attrs={'class': 'text'}))    
    password = forms.CharField(label='Password', help_text=password_help, initial='', max_length=30, required=False, widget=forms.PasswordInput(attrs={'class': 'text'}))
    confirm_password = forms.CharField(label='Re-type password', initial='', max_length=30, required=False, widget=forms.PasswordInput(attrs={'class': 'text'}))
    
    captcha = forms.CharField(label='Please type the word you see in the image', initial='', max_length=128, required=True, widget=forms.TextInput(attrs={'class': 'vTextField'}))

    def __init__(self, *args, **kwargs):
        self.word = kwargs['word']
        del kwargs['word']
        
        super(SignupForm, self).__init__(*args, **kwargs)        

    def clean_email(self):
        value = self.cleaned_data['email']
        
        try:
            account = Account.objects.get(email=value)
        except Account.DoesNotExist:
            pass
        else:
            raise forms.ValidationError("The email address is already used.")
            
        return value

    def clean_captcha(self):
        value = self.cleaned_data['captcha']
        if value != self.word:
            self.data['captcha'] = ''
            raise forms.ValidationError("Please fill in this code.")
        
        return value

    def clean(self):
        if self.cleaned_data['method'] == 'email':        
            email = self.cleaned_data.get('email')                
            password = self.cleaned_data.get('password')
            confirm_password = self.cleaned_data.get('confirm_password')
            
            # must I use a forms.ValidationError()? must this be a sequence?
            # the documentation isn't clear..
            if not email:
                self.errors['email'] = "This field is required."            
            if not password:
                self.errors['password'] = "This field is required."
            if not confirm_password:
                self.errors['confirm_password'] = "This field is required."
            
            if password or confirm_password:
                if password != confirm_password:                
                    self.data['password'] = ''
                    self.data['confirm_password'] = ''
                    raise forms.ValidationError("The Passwords don't match.")
                else:
                    if len(password) < 6:
                        self._errors['password'] = "Passwords must be at least 6 characters long."
                        self.data['password'] = ''
                        self.data['confirm_password'] = ''
            
            return self.cleaned_data
            
        else:
            # TODO: do some basic checks to make sure this is actually a URL..
            return self.cleaned_data
        
    def save(self):
        data = self.cleaned_data               
                    
        account = Account(
            firstname=data['firstname'],
            lastname=data['lastname'],            
            email=data['email'],
            is_active=True,
        )            
        account.set_password(data['password'])            
        account.save()
        
        # email the password to the user                
        from django.core.mail import send_mail
        from django.template import Template, Context, loader  
        context = Context({            
            'account': account,
            'password': data['password'],
            'sitename': settings.SITENAME,
            'seymour_domain': settings.SEYMOUR_DOMAIN            
        })
        
        subject = u"Welcome to %s" % (settings.SITENAME)
        t = loader.get_template('emails/account_added.email')            
        
        email_body = t.render(context)
        if settings.DEBUG:
            print "Subject: " + subject.encode('utf8')
            print "-"*80
            print email_body.encode('utf8')
        else:
            send_mail(subject, email_body, settings.EMAIL_FROM, [account.email], fail_silently=True)
        
        return account
        
    def get_openid(self):
        # for now handle it all inside the view
        return self.cleaned_data['openid']
        
class ResetPasswordForm(forms.Form):
    email = forms.EmailField(label='Email address', max_length=75, required=True, widget=forms.TextInput(attrs={'class': 'vTextField'}))
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email:            
            try:                            
                account = Account.objects.get(email=email)
            except Account.DoesNotExist:
                raise forms.ValidationError("This email address is not on our system.")
                
            return email
        
    def save(self):        
        import sha
        import random
        
        confirmation_code = sha.new(str(random.random())).hexdigest()[:5].upper()
        
        email = self.cleaned_data['email']
        account = Account.objects.get(email=email)
        account.confirmation_code = confirmation_code
        account.save()
        
        # send email
        from django.core.mail import send_mail
        from django.template import Template, Context, loader  
        context = Context({
            'account': account, 
            'sitename': settings.SITENAME,
            'seymour_domain': settings.SEYMOUR_DOMAIN   
        })
                
        subject = u"[%s] Reset Password Confirmation" % (settings.SITENAME)
        t = loader.get_template('emails/reset_password_confirm.email')
        email_body = t.render(context)
        if settings.DEBUG:
            print "Subject: " + subject.encode('utf8')
            print "-"*80
            print email_body.encode('utf8')
        else:
            send_mail(subject, email_body, settings.EMAIL_FROM, [account.email], fail_silently=True)
    
class ConfirmResetPasswordForm(forms.Form):
    email = forms.EmailField(label='Email address', max_length=75, required=True, widget=forms.TextInput(attrs={'class': 'vTextField'}))

templates/accounts/confirm_reset.html
{% extends "guest_base.html" %}

{% load form_tags %}

{% block content %}

<p class="note">Please fill in your email address and the confirmation code
we emailed you. If you followed the link that was in the email, it will be 
prefilled automatically and all you have to do to receive a new password is 
submit the form.
<strong>We will reset your password and email it to you.</strong></p>

<form action="/confirm-reset/" method="post" id="confirmresetform">

{% formfield form.email %}

{% formfield form.confirmation_code %}

<div>
<input type="submit" class="button" value="Reset my Password">
</div>
</form>

<script type="text/javascript">
<!--
document.getElementById('id_email').focus()
//-->
</script>
{% endblock %}

templates/accounts/edit_profile.html
{% extends "base.html" %}

{% load form_tags %}

{% block title %}{{sitename}} - View/Edit Profile{% endblock %}

{% block main %}
<div id="main">
<div class="inner">

<h2>View or Edit your Profile</h2>

<form action="/profile/" name="signup_form" method="post">

{% if form.non_field_errors %}
<div class="non_field_errors">
{{form.non_field_errors}}
</div>
{% endif %}

<h4>Details</h4>

<div class="field_group">
{% formfield form.firstname %}
{% formfield form.lastname %}
</div> <!-- .field_group -->

{% if form.email %}
    {% formfield form.email %}
    
    <h4>Change Password <span class="note">(leave blank to keep current password)</span></h4>
    
    <div class="field_group">
    {% formfield form.password %}
    {% formfield form.confirm_password %}
    </div> <!-- .field_group -->
    
{% else %}
    <p class="note"><strong>Please Note:</strong> Support for changing your OpenID not available at present.</p>
{% endif %}

<input type="submit" name="submit" value="Save" />

</form>


</div> <!-- .inner -->
</div> <!-- #main -->
{% endblock %}

templates/accounts/login.html
{% extends "guest_base.html" %}

{% load form_tags %}

{% block head_extra %}
    {% include "accounts/method_select.html"%}
{% endblock %}

{% block content %}

<form action="/login/" name="login_form" method="post">

{% if form.non_field_errors or openid_failure %}
<div class="non_field_errors">
{% if form.non_field_errors %}
    {{form.non_field_errors}}
{% else %}
    {{openid_failure}}
{% endif %}
</div>
{% endif %}

{% formfield form.method %}

<hr />

<div class="method_div" id="method_email_div" {% ifnotequal method "email" %}style="display: none"{% endifnotequal%}>
{% formfield form.email %}
{% formfield form.password %}
</div> <!-- #method_email -->

<div class="method_div" id="method_openid_div" {% ifnotequal method "openid" %}style="display: none"{% endifnotequal%}>
{% formfield form.openid %}
</div> <!-- #method_openid -->

<input type="submit" name="submit" value="Login" />

</form>

{% endblock %}

templates/accounts/login_error.html
{% extends "guest_base.html" %}

{% load form_tags %}

{% block content %}

<p>While trying to login via OpenID, the following error occurred:</p>

<p class="error">{{error_msg}}</p>

<p>&larr; <a href="/login/">try again</a></p>

{% endblock %}

templates/accounts/method_select.html
<script type="text/javascript" src="/static/js/jquery-1.2.6.min.js"></script>
<script type="text/javascript">
<!--
$(document).ready(function() {    
    $('#field_method input').click(function(element) {
        selected = $(this).val();        
        $('.method_div').css('display', 'none');
        $('#method_'+selected+'_div').css('display', 'block');
    });
});
//-->
</script>

templates/accounts/reset_password.html
{% extends "guest_base.html" %}

{% load form_tags %}

{% block content %}


<p class="note">Enter your email address, then check your mail. We'll send you 
an email with further instructions for resetting your password.</p>


<form action="/reset/" method="post" id="resetpasswordform">

{% formfield form.email %}

<div>
<input type="submit" class="button" value="Next">
</div>
</form>

<script type="text/javascript">
<!--
document.getElementById('id_email').focus()
//-->
</script>

{% endblock %}

templates/accounts/signup.html
{% extends "guest_base.html" %}

{% load form_tags %}

{% block head_extra %}
    {% include "accounts/method_select.html"%}
{% endblock %}

{% block content %}

<form action="/signup/" name="signup_form" method="post">

{% if form.non_field_errors or openid_failure %}
<div class="non_field_errors">
{% if form.non_field_errors %}
    {{form.non_field_errors}}
{% else %}
    {{openid_failure}}
{% endif %}
</div>
{% endif %}

{% formfield form.method %}

<hr />

<div class="method_div" id="method_email_div" {% ifnotequal method "email" %}style="display: none"{% endifnotequal%}>
{% formfield form.email %}
{% formfield form.password %}
{% formfield form.confirm_password %}
</div> <!-- #method_email -->

<div class="method_div" id="method_openid_div" {% ifnotequal method "openid" %}style="display: none"{% endifnotequal%}>
{% formfield form.openid %}
</div> <!-- #method_openid -->

<div class="field">
<label for="id_captcha">Enter the code shown below</label>
{{form.captcha}}
<div class="img"><img src="/captcha/{{hexhash}}/" /></div>
<div id="captcha_error">{% if form.captcha.errors %}<span class="error">{{form.captcha.errors}}</span>{% endif %}</div>
</div>

<input type="submit" name="submit" value="Signup" />

</form>

{% endblock %}

templates/accounts/signup_error.html
{% extends "guest_base.html" %}

{% load form_tags %}

{% block content %}

<p>While trying to signup via OpenID, the following error occurred:</p>

<p class="error">{{error_msg}}</p>

<p>&larr; <a href="/signup/">try again</a></p>

{% endblock %}